In [3]:
import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/polakowo/socialdata2017/master/project/jupyter/data/globalterrorism_cleaned.csv")
df

,year,extended,country,region,state,city,lat,lon,multiple,success,...,nter,claimed,weapontype,nkilled,nkilledter,nwounded,nwoundedter,property,propertyextent,countrycode
0,1970,0,Dominican Republic,Central America & Caribbean,Unknown,Santo Domingo,18.456792,-69.951164,0,1,...,0,0,Unknown,1,0,0,0,0,Unknown,DOM
1,1970,0,Mexico,North America,Unknown,Mexico city,19.432608,-99.133207,0,1,...,7,0,Unknown,0,0,0,0,0,Unknown,MEX
2,1970,0,Philippines,Southeast Asia,Tarlac,Unknown,15.478598,120.599741,0,1,...,0,0,Unknown,1,0,0,0,0,Unknown,PHL
3,1970,0,Greece,Western Europe,Attica,Athens,37.983773,23.728157,0,1,...,0,0,Explosives/Bombs/Dynamite,0,0,0,0,1,Unknown,GRC
4,1970,0,Japan,East Asia,Unknown,Fukouka,33.580412,130.396361,0,1,...,0,0,Incendiary,0,0,0,0,1,Unknown,JPN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152247,2015,0,Burundi,Sub-Saharan Africa,Bujumbura Mairie,Bujumbura,-3.382229,29.366784,0,1,...,0,0,Explosives/Bombs/Dynamite,1,0,10,0,1,Minor (< $1 million),BDI
152248,2015,0,Ireland,Western Europe,Cork,Cork,51.906466,-8.505583,0,0,...,0,0,Explosives/Bombs/Dynamite,0,0,0,0,0,Unknown,IRL
152249,2015,0,Philippines,Southeast Asia,Lanao del Sur,East Basak,7.999676,124.299806,0,1,...,0,0,Firearms,1,0,2,0,0,Unknown,PHL
152250,2015,0,Somalia,Sub-Saharan Africa,Middle Juba,Saacow,1.642952,42.450358,0,1,...,0,0,Unknown,5,0,0,0,0,Unknown,SOM
152251,2015,1,Libya,Middle East & North Africa,Jufra,Zillah,28.549558,17.537850,0,1,...,0,0,Firearms,0,0,0,0,0,Unknown,LBY

In [25]:
# Group by country code and sum the killed column
killed_by_country = df.groupby(['countrycode', 'country','year'])['nkilled'].sum().reset_index()


killed_by_country=killed_by_country.sort_values(by='year',ascending=True)
killed_by_country.to_csv("killed_by_country.csv",index=False)